on: [push]
jobs:
  test:
    runs-on: windows-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - uses: actions/checkout@v3

      - name: Get admb and put in path, windows
        run: |
          Invoke-WebRequest -Uri https://github.com/admb-project/admb/releases/download/admb-13.1/admb-13.1-windows.zip -OutFile "D:\a\admb-13.1.zip"
          Expand-Archive -LiteralPath "D:\a\admb-13.1.zip" -DestinationPath "D:\a\"
          echo "D:\a\ADMB-13.1\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'release'
          rtools-version: '42'
          windows-path-include-rtools: true

      # this step added to change gcc version from 10 to 12
      # https://github.com/marketplace/actions/install-mingw
      - name: Set up MinGW for Windows
        if: matrix.config.os == 'windows-latest'
        uses: egor-tensin/setup-mingw@v2
        with:
          platform: x64

      - name: get info on gcc version
        run: |
          g++ -v

      - name: get info on path
        run: |
          echo $env:GITHUB_PATH

      - name: compile ADMB example
        run: |
          cd D:\a\ADMB-13.1\examples\admb\simple
          admb simple
          ./simple